# language: yaml
name: Deploy Test Version

on:
  workflow_run:
    workflows: [ "Test code formatting and linting" ]
    types:
      - completed

jobs:
  deploy:
    name: Deploying Test ğŸš€ SMA
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required for WIF
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/987661761927/locations/global/workloadIdentityPools/github/providers/my-repo
          service_account: github-actions-deployer@sma-extreme-heat-policy.iam.gserviceaccount.com
          # Optional: keep or remove; must match below if used
          project_id: sma-extreme-heat-policy

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: sma-extreme-heat-policy

      - name: Building (ğŸ—ï¸) and Deploying (ğŸš€)
        run: |
          gcloud builds submit \
            --project=sma-extreme-heat-policy \
            --substitutions=_REPO_NAME="extreme-heat-tool-test",_PROJ_NAME="sma-extreme-heat-policy",_IMG_NAME="test"