# .github/workflows/deploy.yml
name: Deploy ğŸš€ SMA to Google Cloud Run (â˜ğŸƒ)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: Deploying ğŸš€ SMA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # language: yaml
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: 'sma-extreme-heat-policy'
          workload_identity_provider: projects/987661761927/locations/global/workloadIdentityPools/github/providers/my-repo
          service_account: 987661761927-compute@developer.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: heat-stress-scale

      - name: Building (ğŸ—ï¸) and Deploying (ğŸš€)
        run: |
          gcloud builds submit \
            --project=sma-extreme-heat-policy \
            --substitutions=_REPO_NAME="extreme-heat-tool-test",_PROJ_NAME="sma-extreme-heat-policy",_IMG_NAME="test"